
export enum ValidateProfileData {
    INCORRECT_USER_DATA = 'INCORRECT_USER_DATA',
    INCORRECT_AGE = "INCORRECT_AGE",
    INCORRECT_COUNTRY = "INCORRECT_COUNTRY",
    INCORRECT_SERVER = 'INCORRECT_SERVER',
    INCORRECT_DATA = 'INCORRECT_DATA',
    INCORRECT_CITY = "INCORRECT_CITY"

}